def compute_reward(self, input_item, predicted_text) -> Tuple[float, Dict]:
    """
    Compute the reward for converting question and database tables into SQL query.

    Args:
        input_item (dict): Input item containing the question.
        predicted_text (str): Predicted SQL query generated by the model.

    Returns:
        Tuple[float, Dict]: Reward value and a dictionary of metrics.
    """

    # Initialize reward and metrics
    reward = 0.0
    metrics = {}

    # Check if the predicted query is empty
    if not predicted_text.strip():
        return -10.0, {"error_type": "Empty Query"}

    # Calculate accuracy using sql_query_execution_feedback function
    feedback_dict = self.sql_query_execution_feedback(input_item, predicted_text)
    accuracy = feedback_dict.get("accuracy", 0.0)
    metrics["accuracy"] = accuracy

    # Check for precision and recall
    if accuracy == 1.0:
        precision = 1.0
        recall = 1.0
    else:
        precision = feedback_dict.get("precision", 0.0)
        recall = feedback_dict.get("recall", 0.0)

    metrics["precision"] = precision
    metrics["recall"] = recall

    # Calculate F1 score
    f1 = (2 * precision * recall) / (precision + recall) if precision + recall > 0 else -1.0
    metrics["f1"] = f1

    # Check for IoU and error type
    iou = feedback_dict.get("iou", 0.0)
    error_type = feedback_dict.get("error_type")
    error_reason = feedback_dict.get("error_reason")

    metrics["iou"] = iou
    if error_type:
        metrics["error_type"] = error_type
    else:
        metrics["error_type"] = "No Error"

    # Check for error reason
    if error_type == "Invalid Query":
        metrics["error_reason"] = feedback_dict.get("error_reason", "")

    # Calculate reward based on accuracy and missed keywords
    base_penalty = 1.0
    penalty = base_penalty - abs(missed_key_words(base_penalty, input_item['input'], predicted_text)) if len(input_item['input'].split()) > 0 else -10.0

    # Reward for correct query
    reward += accuracy * 5.0

    # Penalty for missed keywords
    reward -= penalty

    return reward, metrics
