def compute_reward(self, input_item, predicted_text) -> Tuple[float, Dict]:
    """
    Compute the reward for converting question and database tables into SQL query.

    Args:
        input_item (dict): Input item containing the question.
        predicted_text (str): Predicted SQL query generated by the model.

    Returns:
        Tuple[float, Dict]: Reward value and a dictionary of metrics.
    """

    # Initialize reward and metrics
    reward = 0.0
    metrics = {}

    # Check if the predicted query is empty
    if not predicted_text.strip():
        return -10.0, {"error_type": "Empty Query"}

    # Calculate accuracy using sql_query_execution_feedback function
    feedback_dict = self.sql_query_execution_feedback(input_item, predicted_text)
    accuracy = feedback_dict.get("accuracy", 0.0)
    metrics["accuracy"] = accuracy

    # Check for precision and recall
    if accuracy == 1.0:
        precision = 1.0
        recall = 1.0
    else:
        precision = feedback_dict.get("precision", 0.0)
        recall = feedback_dict.get("recall", 0.0)

    metrics["precision"] = precision
    metrics["recall"] = recall

    # Calculate f1 score
    if precision + recall == 0.0:
        f1 = 0.0
    else:
        f1 = 2 * (precision * recall) / (precision + recall)
    metrics["f1"] = f1

    # Check for IoU
    iou = feedback_dict.get("iou", 0.0)

    metrics["iou"] = iou

    # Calculate error type and reason
    if "error_type" in feedback_dict:
        error_type = feedback_dict["error_type"]
        error_reason = feedback_dict["error_reason"]
    else:
        error_type = None
        error_reason = None

    metrics["error_type"] = error_type
    metrics["error_reason"] = error_reason

    # Calculate reward based on accuracy and missed keywords
    base_penalty = 0.1
    penalty = base_penalty - abs(missed_key_words(base_penalty, input_item['input'], predicted_text))
    if len(input_item['input'].split()) > 10:
        penalty *= 0.5

    # Ensure reward is not negative
    reward = max(reward, 0.0)

    return reward, metrics
